import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page. */
export const s = {
  pageHeader: { padding: "24px 32px 10px" } satisfies CSSProperties,
  pageTitle: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  pageSubtitle: { fontSize: 14, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,
  body: {
    margin: "14px 32px 44px",
    display: "grid",
    gridTemplateColumns: "minmax(280px, 1fr) minmax(320px, 1.4fr)",
    gap: 20,
    alignItems: "start",
  } satisfies CSSProperties,
  filter: {
    width: "100%",
    padding: "8px 10px",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-elevated)",
    color: "inherit",
    marginBottom: 10,
  } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  row: (selected: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    textAlign: "left",
    padding: "8px 10px",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: selected ? "var(--accent)" : "var(--border)",
    background: "var(--bg-elevated)",
    color: "inherit",
    cursor: "pointer",
  }),
  path: { flex: 1, fontFamily: "var(--font-mono, monospace)", fontSize: 12, wordBreak: "break-all" } satisfies CSSProperties,
  note: { fontSize: 13, color: "var(--text-secondary)", marginTop: 10 } satisfies CSSProperties,
  detail: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  detailMeta: { display: "flex", alignItems: "center", gap: 12, fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  select: {
    padding: "6px 8px",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-elevated)",
    color: "inherit",
  } satisfies CSSProperties,
  prompt: { color: "var(--text-muted)", fontSize: 14, padding: 24 } satisfies CSSProperties,
};
