import type { CSSProperties } from "react";

const border = {
  borderWidth: 1,
  borderStyle: "solid",
  borderColor: "var(--border)",
} satisfies CSSProperties;

export const s = {
  root: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  /** A card that holds its own SectionLabel (Review focus). */
  card: {
    ...border,
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  /** The top card when there is no verdict to show (same frame as VerdictBanner). */
  plainCard: {
    ...border,
    display: "flex",
    gap: 18,
    alignItems: "flex-start",
    padding: 18,
    borderRadius: 10,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  plainMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  action: { display: "inline-flex", alignItems: "center", gap: 10, flexShrink: 0 } satisfies CSSProperties,
  staleHint: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--warn)",
  } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  emptyTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    marginBottom: 4,
  } satisfies CSSProperties,
  /** Same text style as VerdictBanner's summary, so both top-card variants match. */
  summary: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  meta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "4px 16px",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  skeletonStack: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  error: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    fontSize: 14,
    color: "var(--crit)",
  } satisfies CSSProperties,
  /** "Risk areas" heading inside the Intent card; matches SectionLabel's look. */
  subTitle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "0 0 12px 0",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 8,
  } satisfies CSSProperties,
  riskItem: { maxWidth: "100%" } satisfies CSSProperties,
  chip: {
    ...border,
    display: "inline-flex",
    alignItems: "stretch",
    maxWidth: "100%",
    borderRadius: 6,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  chipMain: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    padding: "7px 10px",
    minWidth: 0,
  } satisfies CSSProperties,
  chipTitle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  /** Severity is spelled out too (spec AC10: never colour alone). */
  severityWord: (color: string): CSSProperties => ({
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color,
  }),
  chipRefs: { display: "flex", flexWrap: "wrap", gap: "2px 10px" } satisfies CSSProperties,
  refButton: {
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11.5,
    color: "var(--accent-text)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  chipToggle: {
    display: "grid",
    placeItems: "center",
    width: 30,
    flexShrink: 0,
    background: "transparent",
    border: "none",
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: "var(--border)",
    color: "var(--text-muted)",
    cursor: "pointer",
  } satisfies CSSProperties,
  chevronOpen: { transform: "rotate(180deg)" } satisfies CSSProperties,
  explanation: {
    margin: "6px 0 0 0",
    maxWidth: 560,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  focusList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  focusItem: { display: "flex", alignItems: "baseline", gap: 8 } satisfies CSSProperties,
  focusBullet: { fontSize: 10, color: "var(--accent-text)" } satisfies CSSProperties,
  focusButton: {
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  focusFile: {
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  focusReason: { color: "var(--text-secondary)" } satisfies CSSProperties,
  notice: { display: "block", fontSize: 12, color: "var(--warn)", marginTop: 4 } satisfies CSSProperties,
} as const;
