import type { CSSProperties } from "react";

const card = {
  borderWidth: 1,
  borderStyle: "solid",
  borderColor: "var(--border)",
  borderRadius: 8,
  background: "var(--bg-elevated)",
  padding: 18,
  display: "flex",
  flexDirection: "column",
  gap: 14,
} satisfies CSSProperties;

export const s = {
  root: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  card,
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  spacer: { marginLeft: "auto" } satisfies CSSProperties,
  staleHint: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--warn)",
  } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  summary: {
    margin: 0,
    fontSize: 15,
    lineHeight: 1.55,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  skeletonStack: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  error: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    fontSize: 14,
    color: "var(--crit)",
  } satisfies CSSProperties,
  cards: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 16,
  } satisfies CSSProperties,
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  riskHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  severity: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    fontWeight: 700,
    color,
  }),
  explanation: {
    margin: "6px 0 0 0",
    fontSize: 14,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  refRow: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 6 } satisfies CSSProperties,
  linkButton: {
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
    color: "var(--accent-text)",
    textDecoration: "underline",
  } satisfies CSSProperties,
  focusReason: { color: "var(--text-secondary)", fontFamily: "inherit" } satisfies CSSProperties,
  notice: { fontSize: 12, color: "var(--warn)", marginLeft: 8 } satisfies CSSProperties,
} as const;
