import type { CSSProperties } from "react";

export const s = {
  wrap: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    paddingTop: 12,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  toggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "transparent",
    borderWidth: 0,
    padding: 0,
    width: "100%",
    minWidth: 0,
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 600,
    textAlign: "left",
  } satisfies CSSProperties,
  toggleTitle: {
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  chevron: {
    marginLeft: "auto",
    display: "inline-flex",
    flexShrink: 0,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  } satisfies CSSProperties,
  row: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
    padding: "10px 0 10px 16px",
    position: "relative",
    fontSize: 13,
    color: "var(--text-secondary)",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
  } satisfies CSSProperties,
  bullet: {
    position: "absolute",
    left: 4,
    top: 17,
    width: 4,
    height: 4,
    borderRadius: 99,
    background: "var(--text-muted)",
  } satisfies CSSProperties,
  rowHead: {
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: "0 8px",
    minWidth: 0,
  } satisfies CSSProperties,
  link: {
    color: "var(--accent)",
    fontWeight: 600,
    textDecoration: "none",
    flexShrink: 0,
  } satisfies CSSProperties,
  title: {
    minWidth: 0,
    overflowWrap: "anywhere",
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  meta: {
    fontSize: 12,
    color: "var(--text-muted)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  chips: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    minWidth: 0,
  } satisfies CSSProperties,
  chipItem: {
    minWidth: 0,
    maxWidth: "100%",
  } satisfies CSSProperties,
  chip: {
    display: "block",
    maxWidth: "100%",
    padding: "1px 6px",
    borderRadius: 4,
    fontSize: 11,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  muted: {
    fontSize: 14,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  status: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "var(--warn)",
  } satisfies CSSProperties,
  skeletonStack: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
} as const;
