import type { CSSProperties } from "react";

export const s = {
  card: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  skeletonStack: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  muted: {
    fontSize: 14,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  degraded: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  root: {
    minWidth: 0, // a grid cell must not be blown out by a long path
  } satisfies CSSProperties,
  statsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 10,
  } satisfies CSSProperties,
  stats: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "6px 16px",
    margin: 0,
    minWidth: 0,
  } satisfies CSSProperties,
  stat: {
    display: "flex",
    flexDirection: "row-reverse", // DOM order is term then value; shown as "3 callers"
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 5,
  } satisfies CSSProperties,
  statIcon: {
    display: "inline-flex",
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  statValue: {
    margin: 0,
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  groups: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  group: {
    minWidth: 0,
  } satisfies CSSProperties,
  groupToggle: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    background: "var(--bg-hover)",
    borderWidth: 0,
    borderRadius: 6,
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13,
    textAlign: "left",
    minWidth: 0,
  } satisfies CSSProperties,
  groupToggleIdle: {
    background: "transparent",
  } satisfies CSSProperties,
  groupIcon: {
    display: "inline-flex",
    flexShrink: 0,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  groupSymbol: {
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  groupCount: {
    marginLeft: "auto",
    flexShrink: 0,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  groupBody: {
    padding: "8px 8px 8px 30px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  callers: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
  } satisfies CSSProperties,
  caller: {
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: "0 8px",
    minWidth: 0,
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  callerArrow: {
    display: "inline-flex",
    alignSelf: "center",
    flexShrink: 0,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  // Paths have no spaces, so they only break with `anywhere`.
  callerLocation: {
    minWidth: 0,
    maxWidth: "100%",
    overflowWrap: "anywhere",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  callerLink: {
    color: "var(--text-primary)",
    textDecoration: "none",
  } satisfies CSSProperties,
  callerName: {
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  chipRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    minWidth: 0,
  } satisfies CSSProperties,
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
    maxWidth: "100%",
    padding: "2px 8px",
    borderRadius: 5,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: 1.4,
  } satisfies CSSProperties,
  chipText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  chipIcon: {
    display: "inline-flex",
    flexShrink: 0,
  } satisfies CSSProperties,
  limitHint: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
