import type { CSSProperties } from "react";

export const s = {
  card: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  skeletonStack: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  muted: {
    fontSize: 14,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  degraded: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  stats: {
    display: "flex",
    flexWrap: "wrap",
    gap: 18,
    margin: 0,
  } satisfies CSSProperties,
  stat: {
    display: "flex",
    flexDirection: "row-reverse", // DOM order is term then value; shown as "3 callers"
    justifyContent: "flex-end",
    alignItems: "baseline",
    gap: 6,
  } satisfies CSSProperties,
  statValue: {
    margin: 0,
    fontSize: 20,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  groups: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  group: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 6,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  groupToggle: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    background: "transparent",
    borderWidth: 0,
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 14,
    textAlign: "left",
  } satisfies CSSProperties,
  groupCount: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  groupBody: {
    padding: "0 12px 12px 34px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  callers: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  caller: {
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  callerLink: {
    color: "var(--accent)",
    textDecoration: "none",
  } satisfies CSSProperties,
  chipRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  } satisfies CSSProperties,
  chipLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  limitHint: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
