import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 780 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 14, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  meta: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 14, lineHeight: 1.45 } satisfies CSSProperties,
  link: { fontSize: 12.5, color: "var(--accent)", marginLeft: "auto" } satisfies CSSProperties,
  filter: {
    width: "100%",
    padding: "7px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 13,
    marginBottom: 14,
  } satisfies CSSProperties,
  warning: {
    fontSize: 12.5,
    padding: "8px 12px",
    borderRadius: 8,
    marginBottom: 14,
    border: "1px solid var(--warning, #d9a400)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  message: { fontSize: 13, color: "var(--text-muted)", padding: "12px 0" } satisfies CSSProperties,
  inheritedTitle: { fontSize: 13, fontWeight: 600, margin: "18px 0 8px" } satisfies CSSProperties,
  inheritedList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  inheritedRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12,
  } satisfies CSSProperties,
  mono: { fontFamily: "var(--font-mono, monospace)", flex: 1 } satisfies CSSProperties,
  from: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  previewBox: { marginTop: 16 } satisfies CSSProperties,
};
